# Uncomment the next line to define a global platform for your project
use_frameworks!

target 'quickstart' do
    project "quickstart"
    workspace 'quickstart'
        pod 'MappedIn', '2.0.1-beta'
end
