# Uncomment the next line to define a global platform for your project
use_frameworks!

target 'ios-sdk-app' do
    project "ios-sdk-app"
    workspace 'ios-sdk-app'
        pod 'MappedIn', '5.8.2'
end
